# Generated by Django 3.2.2 on 2021-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_alter_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(),
        ),
    ]
